//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.15 at 04:32:26 PM IST 
//


package com.configurations.businessCalendarConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Range of business hours: from 00:00 to 24:00.  [9:30 - 17:30[ means 8 hours per day.
 * 
 * <p>Java class for BusinessHours complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessHours"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="startHourMinute" use="required" type="{}HourMinute" /&gt;
 *       &lt;attribute name="endHourMinute" use="required" type="{}HourMinute" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessHours")
public class BusinessHours {

    @XmlAttribute(name = "startHourMinute", required = true)
    protected String startHourMinute;
    @XmlAttribute(name = "endHourMinute", required = true)
    protected String endHourMinute;

    /**
     * Gets the value of the startHourMinute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartHourMinute() {
        return startHourMinute;
    }

    /**
     * Sets the value of the startHourMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartHourMinute(String value) {
        this.startHourMinute = value;
    }

    /**
     * Gets the value of the endHourMinute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndHourMinute() {
        return endHourMinute;
    }

    /**
     * Sets the value of the endHourMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndHourMinute(String value) {
        this.endHourMinute = value;
    }

}
